# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_bram/design_bram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_bram || ORIG_REF_NAME==design_bram} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_processing_system7_0_0/design_bram_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_bram_processing_system7_0_0 || ORIG_REF_NAME==design_bram_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_axi_bram_ctrl_0_0/design_bram_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_bram_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_bram_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_axi_bram_ctrl_0_bram_0/design_bram_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_bram_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_bram_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_rst_ps7_0_50M_0/design_bram_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_bram_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_bram_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_axi_bram_ctrl_1_0/design_bram_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_bram_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_bram_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_blk_mem_gen_0_1/design_bram_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_bram_blk_mem_gen_0_1 || ORIG_REF_NAME==design_bram_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_xbar_0/design_bram_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_bram_xbar_0 || ORIG_REF_NAME==design_bram_xbar_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_axi_interconnect_0_0/design_bram_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_bram_axi_interconnect_0_0 || ORIG_REF_NAME==design_bram_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_auto_pc_0/design_bram_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_bram_auto_pc_0 || ORIG_REF_NAME==design_bram_auto_pc_0} -quiet] -quiet

# XDC: i:/mtech/1sem/e-books/ES ZG 626 Hardware software co-design/project_i2s/bram/bram.gen/sources_1/bd/design_bram/design_bram_ooc.xdc
