# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: i:/mtech/1sem/e-books/ES ZG 626 Hardware software co-design/project_i2s/bram/bram.srcs/sources_1/bd/design_bram/ip/design_bram_axi_bram_ctrl_0_bram_0/design_bram_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'design_bram_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/mtech/1sem/e-books/ES ZG 626 Hardware software co-design/project_i2s/bram/bram.gen/sources_1/bd/design_bram/ip/design_bram_axi_bram_ctrl_0_bram_0/design_bram_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_bram_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: i:/mtech/1sem/e-books/ES ZG 626 Hardware software co-design/project_i2s/bram/bram.srcs/sources_1/bd/design_bram/ip/design_bram_axi_bram_ctrl_0_bram_0/design_bram_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'design_bram_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/mtech/1sem/e-books/ES ZG 626 Hardware software co-design/project_i2s/bram/bram.gen/sources_1/bd/design_bram/ip/design_bram_axi_bram_ctrl_0_bram_0/design_bram_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_bram_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
